# Generated by Django 5.2.12 on 2026-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0007_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
