# Generated by Django 5.2.12 on 2026-04-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0010_category_alter_ad_price_alter_ad_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ads",
                to="ads.category",
            ),
            preserve_default=False,
        ),
    ]
