# Generated by Django 6.0.4 on 2026-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_adphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
